config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  
  root "pages#home" #controller # action / method
  get '/about', to: 'pages#about' # sending it to the pages controller, about action
  get '/help', to: 'pages#help'
  
  resources :todos # gives all of the CRUD routes
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    # I don't think you need this but we'll leave it
  end
  
  def about
    
  end
  
  def help
    
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :show, :destroy]
  # sets todo in private method so you don't repeat code in each method
  
  def new
    @todo = Todo.new # this @todo is used in the view, initialize here
                     # Todo is capitalized because it's a class
  end
  
  def create
    @todo = Todo.new(todo_params) # instance variable
    if @todo.save # save to DB
      flash[:notice] = "Todo was created successfully!" # flash
    redirect_to todo_path(@todo)   
    else
      render 'new'
    end
  end
  
  def show # action
  end
  
  def edit
  end
  
  def update
    if @todo.update(todo_params)
      flash[:notice] = "Todo was successfully updated"
      redirect_to todo_path(@todo)
     else
      render 'edit'
    end
  end
   
   def index
    @todos = Todo.all # can be named anything (pizza), used plural here because it's multiple
   end
  
  def destroy
    @todo.destroy
    flash[:notice] = "Todo was deleted successfully"
    redirect_to todos_path
  end
  
  
  private # private means only available to this controller
    
    def set_todo
      @todo = Todo.find(params[:id])
    end
  
    def todo_params
      params.require(:todo).permit(:name, :description) #white listing
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
   <ul>
      <li><%= msg %></li>
   </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tdoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>
  This is the about page
</h1>

app/views/pages/help.html.erb
<h1>
  Report
</h1>

app/views/pages/home.html.erb
<h1>
  Hello World
</h1>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <h4>The following errors prevented the todo from being save:</h4>
  <ul>
    <% @todo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @todo  do |f| %>
  <p>
    <%= f.label :name %>  <br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
  </p>
  <p>
  <%= f.submit %>  
  </p>
<% end %>

<%-# label because it's the label, :name is the DB column%>

app/views/todos/edit.html.erb
<h1>
  Edit a Todo
</h1>

<%= render 'form' %>

<%= link_to "Show this todo", todo_path(@todo) %> |
<%= link_to "Return to Todos", todos_path %>

app/views/todos/index.html.erb
<h1>
  Todos
</h1>

<p>
  <%= link_to "Create a Todo", new_todo_path %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% @todos.each do |anything| %>
  <tr>
    <td><%= anything.name %></td>
    <td><%= anything.description %></td>
    <td><%= link_to "Edit", edit_todo_path(anything) %></td>
    <td><%= link_to "Show", todo_path(anything) %></td>
    <td><%= link_to "Delete", todo_path(anything), method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>

<% if false %>
@todos is calling the @todos variable 
in the index action 
in the Todo controller
anything in pipes can literally be anything

* at first got error 'undefined method each for nil nilclass'
because my 'end' were messed up in the controller *

For edit todo path, the route is 
edit_todo GET    /todos/:id/edit(.:format)
It needs the ID so we give it by saying (anything) which is the object
declared in pipes
<% end %>

app/views/todos/new.html.erb
<h1>
  Create a new todo
</h1>

<%= render 'form' %>

<%= link_to "Back to Todos", todos_path %>

app/views/todos/show.html.erb
<h1>
  Showing a Todo
</h1>

<p>
 Name: <%= @todo.name %> 
</p>
<p>
  Description: <%= @todo.description %> 
</p>
<%= link_to "Edit this todo", edit_todo_path(@todo) %> |
<%= link_to "Back to Todos", todos_path %>

<% if false %>
@todo is calling the @todo variable 
in the SHOW action 
in the Todo controller
<% end %>